// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// RBACDefinitionListerExpansion allows custom methods to be added to
// RBACDefinitionLister.
type RBACDefinitionListerExpansion interface{}
