// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	rbacmanager_v1beta1 "github.com/reactiveops/rbac-manager/pkg/apis/rbacmanager/v1beta1"
	versioned "github.com/reactiveops/rbac-manager/pkg/client/clientset/versioned"
	internalinterfaces "github.com/reactiveops/rbac-manager/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/reactiveops/rbac-manager/pkg/client/listers/rbacmanager/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RBACDefinitionInformer provides access to a shared informer and lister for
// RBACDefinitions.
type RBACDefinitionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.RBACDefinitionLister
}

type rBACDefinitionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewRBACDefinitionInformer constructs a new informer for RBACDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRBACDefinitionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRBACDefinitionInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredRBACDefinitionInformer constructs a new informer for RBACDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRBACDefinitionInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacmanagerV1beta1().RBACDefinitions().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RbacmanagerV1beta1().RBACDefinitions().Watch(options)
			},
		},
		&rbacmanager_v1beta1.RBACDefinition{},
		resyncPeriod,
		indexers,
	)
}

func (f *rBACDefinitionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRBACDefinitionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rBACDefinitionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rbacmanager_v1beta1.RBACDefinition{}, f.defaultInformer)
}

func (f *rBACDefinitionInformer) Lister() v1beta1.RBACDefinitionLister {
	return v1beta1.NewRBACDefinitionLister(f.Informer().GetIndexer())
}
