release:
  prerelease: auto
builds:
  - main: ./cmd/manager
    ldflags:
      - -X github.com/schlapzz/rbac-manager/version.Version={{.Version}} -s -w
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarm:
      - 6
      - 7
dockers:
- image_templates:
  - "quay.io/reactiveops/rbac-manager:{{ .FullCommit }}-amd64"
  - "quay.io/reactiveops/rbac-manager:{{ .Tag }}-amd64"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}-amd64"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}.{{ .Minor }}-amd64"
  use: buildx
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "quay.io/reactiveops/rbac-manager:{{ .Tag }}-arm64v8"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}-arm64v8"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}.{{ .Minor }}-arm64v8"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "quay.io/reactiveops/rbac-manager:{{ .Tag }}-armv7"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}-armv7"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}.{{ .Minor }}-armv7"
  use: buildx
  goarch: arm64
  dockerfile: Dockerfile
  build_flag_templates:
  - "--platform=linux/arm/v7"
docker_manifests:
- name_template: quay.io/reactiveops/rbac-manager:{{ .Tag }}
  image_templates:
  - "quay.io/reactiveops/rbac-manager:{{ .Tag }}-amd64"
  - "quay.io/reactiveops/rbac-manager:{{ .Tag }}-arm64v8"
  - "quay.io/reactiveops/rbac-manager:{{ .Tag }}-armv7"
- name_template: quay.io/reactiveops/rbac-manager:v{{ .Major }}
  image_templates:
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}-amd64"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}-arm64v8"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}-armv7"
- name_template: quay.io/reactiveops/rbac-manager:v{{ .Major }}.{{ .Minor }}
  image_templates:
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}.{{ .Minor }}-amd64"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}.{{ .Minor }}-arm64v8"
  - "quay.io/reactiveops/rbac-manager:v{{ .Major }}.{{ .Minor }}-armv7"
