{{ define "config.yaml.tpl"}}
---
apiVersion: rbac-manager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: {{ template "rbac-manager.fullname" . }}
{{ toYaml .Values.content }}
{{ end }}
