// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/reactiveops/rbac-manager/pkg/apis/rbacmanager/v1beta1"
	scheme "github.com/reactiveops/rbac-manager/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RBACDefinitionsGetter has a method to return a RBACDefinitionInterface.
// A group's client should implement this interface.
type RBACDefinitionsGetter interface {
	RBACDefinitions() RBACDefinitionInterface
}

// RBACDefinitionInterface has methods to work with RBACDefinition resources.
type RBACDefinitionInterface interface {
	Create(*v1beta1.RBACDefinition) (*v1beta1.RBACDefinition, error)
	Update(*v1beta1.RBACDefinition) (*v1beta1.RBACDefinition, error)
	UpdateStatus(*v1beta1.RBACDefinition) (*v1beta1.RBACDefinition, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.RBACDefinition, error)
	List(opts v1.ListOptions) (*v1beta1.RBACDefinitionList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.RBACDefinition, err error)
	RBACDefinitionExpansion
}

// rBACDefinitions implements RBACDefinitionInterface
type rBACDefinitions struct {
	client rest.Interface
}

// newRBACDefinitions returns a RBACDefinitions
func newRBACDefinitions(c *RbacmanagerV1beta1Client) *rBACDefinitions {
	return &rBACDefinitions{
		client: c.RESTClient(),
	}
}

// Get takes name of the rBACDefinition, and returns the corresponding rBACDefinition object, and an error if there is any.
func (c *rBACDefinitions) Get(name string, options v1.GetOptions) (result *v1beta1.RBACDefinition, err error) {
	result = &v1beta1.RBACDefinition{}
	err = c.client.Get().
		Resource("rbacdefinitions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RBACDefinitions that match those selectors.
func (c *rBACDefinitions) List(opts v1.ListOptions) (result *v1beta1.RBACDefinitionList, err error) {
	result = &v1beta1.RBACDefinitionList{}
	err = c.client.Get().
		Resource("rbacdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rBACDefinitions.
func (c *rBACDefinitions) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("rbacdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a rBACDefinition and creates it.  Returns the server's representation of the rBACDefinition, and an error, if there is any.
func (c *rBACDefinitions) Create(rBACDefinition *v1beta1.RBACDefinition) (result *v1beta1.RBACDefinition, err error) {
	result = &v1beta1.RBACDefinition{}
	err = c.client.Post().
		Resource("rbacdefinitions").
		Body(rBACDefinition).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rBACDefinition and updates it. Returns the server's representation of the rBACDefinition, and an error, if there is any.
func (c *rBACDefinitions) Update(rBACDefinition *v1beta1.RBACDefinition) (result *v1beta1.RBACDefinition, err error) {
	result = &v1beta1.RBACDefinition{}
	err = c.client.Put().
		Resource("rbacdefinitions").
		Name(rBACDefinition.Name).
		Body(rBACDefinition).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rBACDefinitions) UpdateStatus(rBACDefinition *v1beta1.RBACDefinition) (result *v1beta1.RBACDefinition, err error) {
	result = &v1beta1.RBACDefinition{}
	err = c.client.Put().
		Resource("rbacdefinitions").
		Name(rBACDefinition.Name).
		SubResource("status").
		Body(rBACDefinition).
		Do().
		Into(result)
	return
}

// Delete takes name of the rBACDefinition and deletes it. Returns an error if one occurs.
func (c *rBACDefinitions) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("rbacdefinitions").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rBACDefinitions) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("rbacdefinitions").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rBACDefinition.
func (c *rBACDefinitions) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.RBACDefinition, err error) {
	result = &v1beta1.RBACDefinition{}
	err = c.client.Patch(pt).
		Resource("rbacdefinitions").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
