apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: rbac-manager-everything-example
rbacBindings:
  - name: admins
    subjects:
      - kind: Group
        name: example
    clusterRoleBindings:
      - clusterRole: edit
    roleBindings:
      - clusterRole: admin
        namespace: default
  - name: example-users
    subjects:
      - kind: User
        name: sue@example.com
      - kind: User
        name: joe@example.com
    clusterRoleBindings:
      - clusterRole: edit
    roleBindings:
      - clusterRole: admin
        namespaceSelector:
          matchLabels:
            team: dev
  - name: example-service-account
    subjects:
      - kind: ServiceAccount
        name: example
        namespace: default
        imagePullSecrets:
          - robot-secret
        automountServiceAccountToken: false
    clusterRoleBindings:
      - clusterRole: view
    roleBindings:
      - clusterRole: admin
        namespaceSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - web
                - queue
