apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    rbac-manager: reactiveops
  ownerReferences:
  - apiVersion: rbacmanager.reactiveops.io/v1beta1
    kind: RBACDefinition
    name: rbac-manager-definition-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-rbac-manager
subjects:
- kind: ServiceAccount
  name: test-rbac-manager
  namespace: rbac-manager
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: robot-secret
metadata:
  annotations:
    rbacmanager.reactiveops.io/managed-pull-secrets: robot-secret
  labels:
    rbac-manager: reactiveops
  name: test-rbac-manager
  namespace: rbac-manager
  ownerReferences:
  - apiVersion: rbacmanager.reactiveops.io/v1beta1
    kind: RBACDefinition
    name: rbac-manager-definition-1
