// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/reactiveops/rbac-manager/pkg/client/clientset/versioned/typed/rbacmanager/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeRbacmanagerV1beta1 struct {
	*testing.Fake
}

func (c *FakeRbacmanagerV1beta1) RBACDefinitions() v1beta1.RBACDefinitionInterface {
	return &FakeRBACDefinitions{c}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeRbacmanagerV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
