// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	glog "github.com/golang/glog"
	rbacmanagerv1beta1 "github.com/reactiveops/rbac-manager/pkg/client/clientset/versioned/typed/rbacmanager/v1beta1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	RbacmanagerV1beta1() rbacmanagerv1beta1.RbacmanagerV1beta1Interface
	// Deprecated: please explicitly pick a version if possible.
	Rbacmanager() rbacmanagerv1beta1.RbacmanagerV1beta1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	rbacmanagerV1beta1 *rbacmanagerv1beta1.RbacmanagerV1beta1Client
}

// RbacmanagerV1beta1 retrieves the RbacmanagerV1beta1Client
func (c *Clientset) RbacmanagerV1beta1() rbacmanagerv1beta1.RbacmanagerV1beta1Interface {
	return c.rbacmanagerV1beta1
}

// Deprecated: Rbacmanager retrieves the default version of RbacmanagerClient.
// Please explicitly pick a version.
func (c *Clientset) Rbacmanager() rbacmanagerv1beta1.RbacmanagerV1beta1Interface {
	return c.rbacmanagerV1beta1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.rbacmanagerV1beta1, err = rbacmanagerv1beta1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		glog.Errorf("failed to create the DiscoveryClient: %v", err)
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.rbacmanagerV1beta1 = rbacmanagerv1beta1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.rbacmanagerV1beta1 = rbacmanagerv1beta1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
